### ISSUE TITLE
Add MOM6 kernel

### ISSUE THREAD

**Issue by rabernat** [ocean-eddy-cpt/gcm-filters#1]
Right now we just have a trivial laplacian kernel:

https://github.com/ocean-eddy-cpt/gcm-filters/blob/7b8d2906d0bdacb98846f4e39c3883ed3a3fc44a/gcm_filters/kernels.py#L17-L22

We need to add the kernel for MOM6. This should be based on whatever @NoraLoose is actively using in her notebooks.

**Comment by NoraLoose** [comment]
@gustavo-marques, @sdbachman, and all other MOM6 pros - I am happy to hand this task over to you if you'd like to contribute to gcm-filters (which I heard you do :smiley: ).

The only reason why I am assigned to this issue is that I have filtering code for the NW2 (MOM6) domain. But I haven't done the global domain yet. Would be great to have your expertise here. I think I have some ideas for how to do the global Laplacian for MOM6, so I am happy to discuss these ideas (or leave it completely up to you if you prefer).  Just wanted to mention this, because I didn't want to give the false impression that I want to do all kernel implementations for all models. :nerd_face:

**Comment by gustavo-marques** [comment]
Sounds good! Thanks, @NoraLoose. I will talk to @sdbachman and we will get back to you.

**Comment by NoraLoose** [comment]
This issue was accidentally closed.

**Comment by iangrooms** [comment]
We have both scalar and vector Laplacians for MOM6 now, so I'm closing this issue.
