### ISSUE TITLE
Numerical Instability

### ISSUE THREAD

**Issue by hmkhatri** [ocean-eddy-cpt/gcm-filters#33]
I was testing the Gaussian filter for varying coarsening factor and n_steps. The instability problem is not completely resolved after stage order update #32.  

I filtered SSH (very smooth field) and ocean depth (relatively noisy field) from a 1/8 deg MOM6 global simulation. For n_steps = 50 and above (filter_scale=40), the filtering starts to fail. 

![image](https://user-images.githubusercontent.com/17830036/113886037-5ad52380-978e-11eb-8502-811d4a923d3b.png)

**Comment by iangrooms** [comment]
I'll take a look at this, but first I want to comment that the fix is supposed to make the stability _better_, but I don't expect to be able to completely remove instability for any possible filter spec. 40 is a pretty huge filter factor; it would take a 0.1 degree model to 4 degrees. For that extreme of an amount of filtering you might want to just start by coarsening.

**Comment by hmkhatri** [comment]
@iangrooms Thanks for the clarification. It would be nice to have a small section on the instability issue in the documentation. As you have suggested, for filtering to very large scales, one would need to use a combination of gaussian/taper filtering and coarsening. I think it would be useful to have a tutorial on this approach. I will prepare a small tutorial on this and share it soon.

**Comment by iangrooms** [comment]
For a Gaussian filter with scale factor 40 the default number of steps (in 2D) leads to 71 total stages (including one biharmonic, i.e. same as setting `n_steps=72`). In my simple tests I do see some transient amplification during the stages, but not enough to mess up the final result. If I force `n_steps=200` instead of the default then I do see enough transient amplification to completely ruin the final result. Is there are reason for using 200 steps instead of the default? The default should get you better than 1% accuracy. (It's also worth making sure that the filtering happens in double precision even when the data is single precision, but I think that's already enforced in the code.)

The default setup (Gaussian) appears to be OK out to filter factors of 50 for input data with a flat spectrum. (It will do better for input data that have steeper spectra.) To implement a better stage order would require us to actually know the spectrum of the discrete Laplacian (or at least have an estimate for the largest eigenvalue), which we don't have. So I think anyone who wants to use scale factors  > 50 or larger-than-default `n_steps` should pursue a coarsen-then-filter strategy. It would be good to have a small tutorial on this.

**Comment by hmkhatri** [comment]
@iangrooms Thanks for looking into this. I was not aware that there is a default value set for `n_steps` based on `scale_factor`. I was trying different values of `n_steps` to testing the effect on the final result as I did not know an estimate for the optimal value for `n_steps`. Anyway, I will keep working on testing it with more data.
