### ISSUE TITLE
Team meeting 🗓

### ISSUE THREAD

**Issue by jbusecke** [ocean-eddy-cpt/gcm-filters#35]
Hi everyone, 

@rabernat has asked me to organize a meeting within this group so that we can discuss a roadmap to the *first release* and the *JOSS paper*.

I have created a [when2meet poll](https://www.when2meet.com/?11791882-ZHBYs) for next week (May 3-7). Please indicate your availability, so we can see if any time next week works for everyone.

I'll then set up an agenda/zoom call once we are settled on a date.

Also, please tag anyone that should attend if I did not catch them below.

@NoraLoose @iangrooms @gustavo-marques @arthurBarthe @hmkhatri @ElizabethYankovsky

Hope to see you all next week!

**Comment by rabernat** [comment]
Thanks for organizing Julius!

**Comment by rabernat** [comment]
Let's also include @tomnicholas.

**Comment by gustavo-marques** [comment]
@sdbachman might also want to join us.

**Comment by jbusecke** [comment]
So far it seems that the two possible spots are Wednesday **May 5 (11am-noon)** and **Fri May 7 (1-2pm)**. 
I will do a final check on Monday, but if things dont change I suggest the Wednesday spot. 

Will confirm next week. Enjoy the weekend everyone.

**Comment by iangrooms** [comment]
Times are EST?

**Comment by jbusecke** [comment]
Yes, times are EST. Sorry, should have made that more clear. Does that change anyone's availability?

**Comment by jbusecke** [comment]
Ok it looks to me like Wednesday (May 5th 11AM EST) is the final choice.

I created a zoom call here: https://columbiauniversity.zoom.us/j/99724010848

Please let me know if there are any more questions. Looking forward to see you all Wednesday

**Comment by rabernat** [comment]
I have created an agenda for tomorrow's meeting: https://docs.google.com/document/d/1or6Y1adXHnn-r1M0FhOLH5qwp24Gobm4RPm4S3tuKsA/edit?usp=sharing

Anyone should feel free to add additional items. Looking forward to the discussion!

**Comment by jbusecke** [comment]
Do people here think it would be helpful if I create two github projects that can serve as todo/progress for both goals (release + paper)?

**Comment by sdbachman** [comment]
I ended up filling out the poll but I think I'm going to respectfully bow out of this effort, as I'm not sure I'll have anything useful to contribute and I don't want to be flotsam.

**Comment by rabernat** [comment]
> I'm going to respectfully bow out of this effort

A few points:
- "this effort", the gcm-filters package, will be an ongoing for a long time.
- I'm quite certain anyone who has used the package has something to contribute 😊 
- Authorship on the JOSS paper will be open to anyone who is interested
- Attending today's meeting is not a prerequisite for future involvement

So @sdbachman - I completely understand bowing out due to time constraints / priority setting (I should learn how to do that myself 🙃 ) - however, your stated reason ("not having anything useful to contribute") is, IMO, not valid 😝 . We'd love to continue to get your comments and feedback on the package, and examples of how you are using it. One task we have to do before submitting the JOSS paper is expand the documentation, so there will be more opportunities to engage there.

**Comment by sdbachman** [comment]
![image](https://user-images.githubusercontent.com/20640546/117149325-5ba0ab80-ad74-11eb-821b-c7a345835073.png)
I appreciate the very friendly arm-twisting @rabernat, so I'll attend :)

**Comment by jbusecke** [comment]
Thank you all for the productive meeting. I am going to close this issue, and we can keep the discussion going on the issue tracker.
